theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
title: Olek Gierczak
logo: /assets/headshot.png
description: PhD Student at NEU studying PL
name: Olek Gierczak

github:
  is_user_page: false
  is_project_page: false
